sudo: required

cache: cargo

services:
  - docker

script:
  - docker pull frederickzh/mingw:rust-stable
  - docker build -t frederickzh/mingw:rust-stable .
  - docker run -it frederickzh/mingw:rust-stable "/apps/rust-test.sh"
